version: '3'
services:
    mysql:
        platform: linux/x86_64
        build: ./mysql
        environment:
            - MYSQL_DATABASE=sample
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=tiger
            - TZ=Asia/Seoul
        ports:
            - "3306:3306"
